# Path: backend/alembic/script.py.mako

"""add episode_id to appointments

Revision ID: 55e210cf3aef
Revises: d193b211eed9
Create Date: 2026-01-20 07:23:39.907774

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '55e210cf3aef'
down_revision = 'd193b211eed9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_episode_id'), 'appointments', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_episode_id'), table_name='appointments')
    # ### end Alembic commands ###
