# Path: backend/alembic/script.py.mako

"""patient user ownership

Revision ID: d61707949f9d
Revises: 55e210cf3aef
Create Date: 2026-01-20 14:31:54.248805

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'd61707949f9d'
down_revision = '55e210cf3aef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_column('patients', 'user_id')
    # ### end Alembic commands ###
